# Generated by Django 5.1.5 on 2025-01-15 20:28

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(db_index=True, default=False, help_text='Current online status')),
                ('last_time_online', models.DateTimeField(blank=True, help_text='Last time user was online', null=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Email verification status')),
                ('date_of_birth', models.DateField(blank=True, help_text="User's date of birth", null=True)),
                ('preferred_language', models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('zh', 'Chinese')], help_text='Preferred interface language', max_length=15, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, help_text="User's country of residence", max_length=2, null=True)),
                ('bio', models.TextField(blank=True, help_text="User's biography", max_length=500, null=True)),
                ('current_role', models.CharField(blank=True, help_text="User's current professional role", max_length=40, null=True)),
                ('profile_progress', models.PositiveSmallIntegerField(blank=True, help_text='Profile completion percentage', null=True)),
                ('skill_level', models.PositiveSmallIntegerField(blank=True, help_text='General skill level', null=True)),
                ('analytical_level', models.PositiveSmallIntegerField(blank=True, help_text='Analytical skill level', null=True)),
                ('startup_corporate_level', models.PositiveSmallIntegerField(blank=True, help_text='Startup vs corporate experience level', null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile_pics/fallback-profile-image.png', help_text="User's profile picture", upload_to='profile_pics/')),
                ('github_profile', models.URLField(blank=True, help_text='GitHub profile URL', null=True, validators=[django.core.validators.URLValidator()])),
                ('instagram_profile', models.URLField(blank=True, help_text='Instagram profile URL', null=True, validators=[django.core.validators.URLValidator()])),
                ('linkedin_profile', models.URLField(blank=True, help_text='LinkedIn profile URL', null=True, validators=[django.core.validators.URLValidator()])),
                ('looking_for_mentor', models.BooleanField(default=False, help_text='Whether user is looking for a mentor')),
                ('mentor', models.BooleanField(default=False, help_text='Whether user is willing to be a mentor')),
                ('goals', models.TextField(blank=True, help_text="User's professional goals (comma-separated)", null=True)),
                ('user', models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User detail',
                'verbose_name_plural': 'User details',
            },
        ),
    ]
