# Generated by Django 5.1.5 on 2025-02-11 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_testclass'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the room', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the room', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Last time the room was updated')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the room was created')),
                ('updatedDate', models.DateField(auto_now=True, help_text='Date of last update')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('skill_type', models.CharField(choices=[('LANG', 'Programming Language'), ('FRONT', 'Frontend'), ('BACK', 'Backend'), ('DB', 'Database'), ('DEVOPS', 'DevOps & Cloud'), ('MOBILE', 'Mobile Development'), ('TEST', 'Testing'), ('OTHER', 'Tools & Others')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='TestClass',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default-profile.png', help_text="User's profile picture", upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user',
            field=models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='details', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
