# Generated by Django 5.1.7 on 2025-03-25 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_comment_post_topic_delete_room_comment_post_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='analytical_level',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='skill_level',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='startup_corporate_level',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='likes',
            field=models.ManyToManyField(blank=True, help_text='Users who liked this post', related_name='liked_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of profile likes'),
        ),
    ]
