# Generated by Django 5.1.7 on 2025-03-25 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_comment_post_topic_delete_room_comment_post_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='analytical_level',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='skill_level',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='startup_corporate_level',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='likes',
            field=models.ManyToManyField(blank=True, help_text='Users who liked this profile', related_name='liked_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of profile likes'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('cn', 'Chinese')], help_text='Preferred interface language', max_length=15, null=True),
        ),
    ]
