# Generated by Django 5.1.7 on 2025-03-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_userdetails_analytical_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('cn', 'Chinese')], help_text='Preferred interface language', max_length=15, null=True),
        ),
    ]
