# Generated by Django 5.1.7 on 2025-03-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_post_dislikes_alter_post_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.AlterField(
            model_name='post',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of likes'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('cn', 'Chinese')], help_text='Preferred interface language', max_length=15, null=True),
        ),
    ]
